name: agenda_app
description: App de agenda con categorÃ­as y notificaciones

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Base de datos
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Notificaciones
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  
  # Calendario
  table_calendar: ^3.0.9
  
  # Estado y utilidades
  provider: ^6.1.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true